// Copyright_Team_AriAri


#include "Player/QPlayerController.h"
#include "QLogCategories.h"
#include "InputAction.h"
#include "EnhancedInputSubsystems.h"
#include "UI/QVillageUIManager.h"
#include "UI/QMapWidget.h"
#include "UI/QP2NWidget.h"
#include "EnhancedInputComponent.h"
#include "UI/QInventoryWidget.h"
#include "Character/QPlayer.h"
#include "Character/QDynamicNPC.h"
#include "NPC/QDynamicNPCController.h"
#include "Character/QNPC.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "NPC/QNPCController.h"
#include "Player/QPlayerState.h"
#include "QGameplayTags.h"
#include "Kismet/KismetMathLibrary.h"
#include "NPC/QDynamicNPCController.h"

void AQPlayerController::MulticastBlockInteraction_Implementation()
{
	UE_LOG(LogLogic, Log, TEXT("AQPlayerController::BlockInteraction: êµ¬í˜„ë¨. "));
	//ìƒí˜¸ì‘ìš©ì„ block == ì´ë™ì…ë ¥ì²˜ë¦¬x
	//EnhancedInputComponent ìºìŠ¤íŒ…
	auto* EnhancedInputComponent = Cast<UEnhancedInputComponent>(InputComponent);
	if (EnhancedInputComponent) {
		//ë°”ì¸ë”© í•´ì œ
		EnhancedInputComponent->ClearActionBindings();
	}
	//InputComponentë¥¼ ë¹„í™œì„±í™”
	InputComponent = nullptr;
}

void AQPlayerController::ServerRPCStartMatchMaking_Implementation(AQPlayerController* ClientPC)
{
}

void AQPlayerController::ServerRPCGetProsecutorStatement_Implementation(AQPlayerController* ClientPC)
{
}

void AQPlayerController::ClientRPCGetProsecutorStatement_Implementation(FOpenAIResponse Response)
{
}

void AQPlayerController::ServerRPCGetLawyerStatement_Implementation(AQPlayerController* ClientPC)
{
}

void AQPlayerController::ClientRPCGetLawyerStatement_Implementation(FOpenAIResponse Response)
{
}

void AQPlayerController::ServerRPCGetFinalJudgement_Implementation(AQPlayerController* ClientPC)
{
}

void AQPlayerController::ClientRPCGetFinalJudgement_Implementation(FOpenAIResponse Response)
{
}

void AQPlayerController::ServerRPCTravelToMain_Implementation(AQPlayerController* ClientPC)
{
}

void AQPlayerController::BeginPlay()
{
	Super::BeginPlay();
	
	if (GetNetMode() != NM_DedicatedServer && !HasAuthority()) {
		UE_LOG(LogTemp, Log, TEXT("ğŸ’¡ Local Client PlayerController BeginPlay - VillageUIManager ìƒì„± ì‹œë„"));

		// VillageUIManager ì‹±ê¸€í†¤ ìƒì„±
		AQVillageUIManager::GetInstance(GetWorld());
	}

	//Playerë¡œë¶€í„° EnhancedInput subsystemì„ ê°€ì ¸ì˜¨ë‹¤. 
	auto* SubSystem = ULocalPlayer::GetSubsystem<UEnhancedInputLocalPlayerSubsystem>(GetLocalPlayer());

	if (SubSystem) {
		//mapping contextë¥¼ ì¶”ê°€í•´ì£¼ëŠ”ë°, priorityëŠ” 0
		SubSystem->AddMappingContext(InputMappingContext, 0);
	}

	//villagemanagerë¥¼ ê°€ì ¸ì˜¨ë‹¤
	VillageUIManager = AQVillageUIManager::GetInstance(GetWorld());

	//ê¸°ë³¸ì ìœ¼ë¡œ ë§ˆìš°ìŠ¤ì»¤ì„œ ë³´ì´ê²Œ
	this->bShowMouseCursor = true;
}

void AQPlayerController::SetupInputComponent()
{
	Super::SetupInputComponent();

	//InputComponentëŠ” Actorì˜ ë©¤ë²„ë³€ìˆ˜ì´ë‹¤. ë©¤ë²„ë³€ìˆ˜ë¥¼ EnhancedInputìœ¼ë¡œ ìºìŠ¤íŒ…í•œë‹¤.
	auto* EnhancedInputComponent = Cast<UEnhancedInputComponent>(InputComponent);
	if (EnhancedInputComponent) {
		/*ì•¡ì…˜ì— ëŒ€í•´, íŠ¸ë¦¬ê±° ë˜ë©´ ì½œë°±ë˜ëŠ” í•¨ìˆ˜ë¥¼ ë°”ì¸ë”©í•œë‹¤.*/
		EnhancedInputComponent->BindAction(MoveAction, ETriggerEvent::Triggered, this, &ThisClass::InputMove);
		EnhancedInputComponent->BindAction(TurnAction, ETriggerEvent::Triggered, this, &ThisClass::InputTurn);
		EnhancedInputComponent->BindAction(InteractionAction, ETriggerEvent::Started, this, &ThisClass::InputInteraction);
		EnhancedInputComponent->BindAction(EnableTurnAction, ETriggerEvent::Started, this, &ThisClass::InputEnableTurn);
		EnhancedInputComponent->BindAction(TurnOnOffMapAction, ETriggerEvent::Started, this, &ThisClass::InputTurnOnOffMap);
		EnhancedInputComponent->BindAction(TurnOnOffInventoryAction, ETriggerEvent::Started, this, &ThisClass::InputTurnOnOffInventory);
		EnhancedInputComponent->BindAction(EnableTurnAction, ETriggerEvent::Completed, this, &ThisClass::InputEnableTurn);
	}
}

void AQPlayerController::Tick(float DeltaTime)
{
	if (InputComponent == nullptr) {
		MoveToCourtTimer += DeltaTime;
		if (MoveToCourtTimer >= MoveToCourtTimerMax) {
			// í˜„ì¬ ì›”ë“œì—ì„œ GameStateë¥¼ ê°€ì ¸ì˜´
			TObjectPtr<AQVillageGameState> VillageGameState = GetWorld()->GetGameState<AQVillageGameState>();
			if (!VillageGameState)
			{
				/** @todo ì¸ìˆ˜ í˜•ì‹ë§ê²Œ ë³€í™˜í•˜ê¸°. */
				//VillageGameState->ServerRPCRequestTravelToCourt(this, true);
			}
		}
	}
}

void AQPlayerController::ClientRPCUpdateCanFinishConversP2N_Implementation(bool bResult)
{
	if (bResult)
	{
		TObjectPtr<AQPlayer> _Player = Cast<AQPlayer>(this->GetPawn());

		//1. ìƒëŒ€ë°© NPCë¥¼ ë¶ˆëŸ¬ì˜´
		//2. ìƒëŒ€ë°© NPCì˜ ì»¨íŠ¸ë¡¤ëŸ¬ë¥¼ ë¶ˆëŸ¬ì˜´
		TObjectPtr<AQDynamicNPC> NPC = Cast<AQDynamicNPC>(_Player->GetClosestNPC());

		//ì„œë²„ ëŒ€í™”ë¡œì§ ì‹¤í–‰
		Cast<AQPlayer>(this->GetPawn())->ServerRPCFinishConversation(this, NPC);
	}
	else
	{
		/** @todo ìœ ì§„ : ëŒ€í™”ë¥¼ ì‹œì‘í•  ìˆ˜ ì—†ì„ë•Œ í´ë¼ì´ì–¸íŠ¸ì—ì„œ ì‹¤í–‰ì‹œì¼œì•¼í•˜ëŠ” í•¨ìˆ˜ ì—¬ê¸°ì„œ í˜¸ì¶œ */
		UE_LOG(LogLogic, Log, TEXT("ëŒ€í™”ëë‚´ê¸°ì‹¤íŒ¨!!"));

	}
}

void AQPlayerController::ClientRPCUpdateCanStartConversP2N_Implementation(bool bResult)
{
	if (!bResult)
	{
		UE_LOG(LogLogic, Log, TEXT("ëŒ€í™”ì‹œë„ì‹¤íŒ¨!!"));
		return;
	}
	TObjectPtr<AQPlayer> _Player = Cast<AQPlayer>(this->GetPawn());
	TObjectPtr<AQDynamicNPC> NPC = Cast<AQDynamicNPC>(_Player->GetClosestNPC());
	/*
	 *TObjectPtr<AQDynamicNPCController> DynamicNPCController = Cast<AQDynamicNPCController>(NPC->GetController());
	if (!DynamicNPCController) {
		UE_LOG(LogLogic, Error, TEXT("DynamicNPCControllerê°€ ì—†ìŒ"));
		return;
	}
	*/
	/*ëª¸ ë©ˆì¶”ê¸°*/
	//ë‚´ ëª¸ë©ˆì¶”ê¸°
	FreezePawn();
	//NPCëª¸ë©ˆì¶”ê¸°
	//DynamicNPCController->FreezePawn();
	
	//í”Œë ˆì´ì–´ë¥¼ ëŒ€í™”ì²˜ë¦¬í•œë‹¤. (ì„œë²„)
	Cast<AQPlayer>(this->GetPawn())->ServerRPCStartConversation(this, NPC);
}

void AQPlayerController::ClientRPCStartConversation_Implementation(FOpenAIResponse NPCStartResponse, AQNPC* NPC)
{
	// UE_LOG(LogTemp, Log, TEXT("Player Conversation State Updated. -> %hhd"), LocalPlayerState->GetPlayerConversationState());
	// UE_LOG(LogTemp, Log, TEXT("%s Conversation State Updated. -> %hhd"), *NPC->GetName(), NPC->GetNPCConversationState());

		UE_LOG(LogLogic, Log, TEXT("ClientRPCStartConversation Started."))
		//0. ìƒëŒ€ë°© NPCë¥¼ ë¶ˆëŸ¬ì˜´
		TObjectPtr<AQDynamicNPC> _NPC = Cast<AQDynamicNPC>(NPC);
		if (_NPC == nullptr)
		{
			UE_LOG(LogLogic, Error, TEXT("AQPlayerController::ClientRPCStartConversation_Implementation - _NPC is nullptr."))
			return;
		}

		/** @todo ìœ ì§„ : ì„œë²„ì¸¡ì—ì„œ ëŒ€í™” ì‹œì‘ ë¡œì§ì´ ì„±ê³µì ìœ¼ë¡œ ë§ˆë¬´ë¦¬ ë˜ì—ˆì„ ë–„ ì‹¤í–‰í•  í•¨ìˆ˜ ì—¬ê¸°ì„œ í˜¸ì¶œ */
		/** @todo ìœ ì§„ - ì´ ë¶€ë¶„ì„ Player.cppì— í‘œì‹œí•´ë†“ì€ ë¶€ë¶„ì—ì„œ í˜¸ì¶œí•˜ë©´ ë ë“¯. + nullcheckê°™ì€ê±° ì¶”ê°€ë¡œ í•˜ë©´ã„· ì¢‹ì„ ê²ƒ ê°™ì•„ìš”*/
		//1. UIë¥¼ í‚¨ë‹¤.
		VillageUIManager->TurnOnUI(EVillageUIType::P2N);
	
		//2. P2N Widgetì—ê²Œ ìì‹ ì˜ ì •ë³´ë¥¼ ë„˜ê¸´ë‹¤.
		//ë‚´ ì •ë³´ ë„˜ê²¨ì£¼ê¸°
		Cast<UQP2NWidget>((VillageUIManager->GetActivedVillageWidgets())[EVillageUIType::P2N])->SetConversingPlayer(this);
		//3. P2N Widgetì—ê²Œ NPCì˜ ì •ë³´ë¥¼ ë„˜ê¸´ë‹¤.
		TMap<EVillageUIType, TObjectPtr<UUserWidget>> VillageWidgets = VillageUIManager->GetActivedVillageWidgets();
		TObjectPtr<UQP2NWidget> P2NWidget = Cast<UQP2NWidget>(VillageWidgets[EVillageUIType::P2N]);
		P2NWidget->SetConversingNPC(_NPC);
		P2NWidget->DisplayNPCResponse(NPCStartResponse);
}

void AQPlayerController::ClientRPCUpdateP2NResponse_Implementation(FOpenAIResponse Response)
{
	TMap<EVillageUIType, TObjectPtr<UUserWidget>> VillageWidgets = VillageUIManager->GetActivedVillageWidgets();
	TObjectPtr<UQP2NWidget> P2NWidget = Cast<UQP2NWidget>(VillageWidgets[EVillageUIType::P2N]);
	P2NWidget->DisplayNPCResponse(Response);
}

void AQPlayerController::ClientRPCFinishConversation_Implementation(AQNPC* NPC)
{
	//UE_LOG(LogTemp, Log, TEXT("Player Conversation State Updated. -> %hhd"), LocalPlayerState->GetPlayerConversationState());
	UE_LOG(LogTemp, Log, TEXT("%s Conversation State Updated. -> %hhd"), *NPC->GetName(), NPC->GetNPCConversationState());

		/** @todo ìœ ì§„ : ì„œë²„ì¸¡ì—ì„œ ëŒ€í™” ë§ˆë¬´ë¦¬ ë¡œì§ì´ ì„±ê³µì ìœ¼ë¡œ ë§ˆë¬´ë¦¬ ë˜ì—ˆì„ ë•Œ ì‹¤í–‰í•  í•¨ìˆ˜ ì—¬ê¸°ì„œ í˜¸ì¶œ */
		/** @todo ìœ ì§„ : ëŒ€í™”ë¥¼ ëë‚¼ ìˆ˜ ìˆì„ë•Œ í´ë¼ì´ì–¸íŠ¸ì—ì„œ ì‹¤í–‰ì‹œì¼œì•¼í•˜ëŠ” í•¨ìˆ˜ ì—¬ê¸°ì„œ í˜¸ì¶œ */	
		UnFreezePawn();
		
		//5. UIëˆë‹¤.
		AQVillageUIManager::GetInstance(GetWorld())->TurnOffUI(EVillageUIType::P2N);
}


void AQPlayerController::FreezePawn()
{
	//í° ì •ë³´ ê°€ì ¸ì˜¤ê¸°
	TObjectPtr<APawn> ControlledPawn = this->GetPawn();
	if (!ControlledPawn) {
		return;
	}

	//movement component ê°€ì ¸ì˜¤ê¸°
	TObjectPtr<UCharacterMovementComponent> MovementComponent = ControlledPawn->FindComponentByClass<UCharacterMovementComponent>();
	if (MovementComponent) {
		MovementComponent->StopMovementImmediately();//ì¦‰ì‹œë©ˆì¶¤(ì†ë„ë¥¼ 0ìœ¼ë¡œ ë§Œë“¦)
		MovementComponent->SetComponentTickEnabled(false);//í‹± ë¹„í™œì„±í™”
		MovementComponent->Deactivate();//ì´ë™ ë¹„í™œì„±í™”
	}

	UE_LOG(LogLogic, Log, TEXT("í”Œë ˆì´ì–´ ë©ˆì¶¤."));
}

void AQPlayerController::UnFreezePawn()
{
	//í° ì •ë³´ ê°€ì ¸ì˜¤ê¸°
	TObjectPtr<APawn> ControlledPawn = this->GetPawn();
	if (!ControlledPawn) {
		return;
	}

	//movement component ê°€ì ¸ì˜¤ê¸°
	TObjectPtr<UCharacterMovementComponent> MovementComponent = ControlledPawn->FindComponentByClass<UCharacterMovementComponent>();
	if (MovementComponent) {
		MovementComponent->SetComponentTickEnabled(true);//í‹± í™œì„±í™”
		MovementComponent->Activate(true);//ì´ë™ í™œì„±í™”
	}

	UE_LOG(LogLogic, Log, TEXT("í”Œë ˆì´ì–´ ì´ë™ ì¬ê°œ."));
}




void AQPlayerController::InputEnableTurn(const FInputActionValue& InputValue)
{
	bEnableTurn = InputValue.Get<bool>() ? true : false;
	//ë§ˆìš°ìŠ¤ ì»¤ì„œ ê°ì¶”ê¸°
	this->bShowMouseCursor = InputValue.Get<bool>() ? false : true;
}

void AQPlayerController::InputInteraction(const FInputActionValue& InputValue)
{
	
	//ëŒ€í™”ì‹œì‘í•´ë„ë¼? 
	//0. ìƒëŒ€ë°© NPCë¥¼ ë¶ˆëŸ¬ì˜´
	TObjectPtr<AQPlayer> _Player = Cast<AQPlayer>(this->GetPawn());
	TObjectPtr<AQDynamicNPC> NPC = Cast<AQDynamicNPC>(_Player->GetClosestNPC());
	//1. ë¬¼ì–´ë´„
	Cast<AQPlayer>(GetPawn())->ServerRPCCanStartConversP2N(this, NPC);
	UE_LOG(LogLogic, Log, TEXT("Eë²„íŠ¼ ëˆ„ë¦„!"));
	

}

void AQPlayerController::InputTurnOnOffMap(const FInputActionValue& InputValue)
{

	

	//ì§€ë„ê°€ ì¼œì ¸ìˆëŠ”ì§€, êº¼ì ¸ìˆëŠ”ì§€ì— ë”°ë¼ ì¼¤ì§€ëŒì§€ê°€ ê²°ì •ë¨.
	//ì§€ë„ê°€ ìˆëŠ”ì§€ë¶€í„° í™•ì¸
	if (VillageUIManager->GetActivedVillageWidgets().Contains(EVillageUIType::Map)) {
		TObjectPtr<UQMapWidget> MapWidget = Cast<UQMapWidget>((VillageUIManager->GetActivedVillageWidgets())[EVillageUIType::Map]);

		//ë³´ì´ëŠ” ìƒíƒœê°€ ì•„ë‹ˆë©´ ì¼œê¸°
		if (MapWidget->GetVisibility() != ESlateVisibility::Visible) {
			VillageUIManager->TurnOnUI(EVillageUIType::Map);
		}
		//ë³´ì´ë©´ ë„ê¸°
		else {
			VillageUIManager->TurnOffUI(EVillageUIType::Map);
		}
	}
	else {
		//ì§€ë„ì—†ìœ¼ë©´ UIì¼œê¸°(ìƒì„±)
		VillageUIManager->TurnOnUI(EVillageUIType::Map);
	}
	
}

void AQPlayerController::InputTurnOnOffInventory(const FInputActionValue& InputValue)
{
	//ì¸ë²¤í† ë¦¬ê°€ ì¼œì ¸ìˆëŠ”ì§€, êº¼ì ¸ìˆëŠ”ì§€ì— ë”°ë¼ ì¼¤ì§€ëŒì§€ê°€ ê²°ì •ë¨.
	//ì¸ë²¤í† ë¦¬ê°€ ìˆëŠ”ì§€ë¶€í„° í™•ì¸
	if (VillageUIManager->GetActivedVillageWidgets().Contains(EVillageUIType::Inventory)) {
		TObjectPtr<UQInventoryWidget> InventoryWidget = Cast<UQInventoryWidget>((VillageUIManager->GetActivedVillageWidgets())[EVillageUIType::Inventory]);

		//ë³´ì´ëŠ” ìƒíƒœê°€ ì•„ë‹ˆë©´ ì¼œê¸°
		if (InventoryWidget->GetVisibility() != ESlateVisibility::Visible) {
			VillageUIManager->TurnOnUI(EVillageUIType::Inventory);
		}
		//ë³´ì´ë©´ ë„ê¸°
		else {
			VillageUIManager->TurnOffUI(EVillageUIType::Inventory);
		}
	}
	else {
		//ì§€ë„ì—†ìœ¼ë©´ UIì¼œê¸°(ìƒì„±)
		VillageUIManager->TurnOnUI(EVillageUIType::Inventory);
	}
}

void AQPlayerController::InputTurn(const FInputActionValue& InputValue)
{
	//bEnableTurnì´ trueì¼ë•Œë§Œ í™”ë©´ì „í™˜ì´ ê°€ëŠ¥í•˜ë‹¤.
	if (bEnableTurn) {
		//ë‚´ ê³ ê°œ íšŒì „ê°’ì„ control rotationì— ì „ë‹¬. : ìƒí•˜ì¢Œìš° ê³ ê°¯ì§“
		float Yaw = InputValue.Get<FVector2D>().X;
		float Pitch = InputValue.Get<FVector2D>().Y;
		this->AddYawInput(Yaw);
		this->AddPitchInput(-Pitch);
	}
}



void AQPlayerController::InputMove(const FInputActionValue& InputValue)
{
	
	FVector2D MovementVector = InputValue.Get<FVector2D>();

	//ì• ì´ë™
	if (MovementVector.X != 0) {
		/*ë‚´ê°€ ë°”ë¼ë³´ëŠ” ê³³ ê¸°ì¤€ì˜ ì• ë°©í–¥ì„ êµ¬í•´ì¤Œ*/
		//ë§ˆìš°ìŠ¤ ë°©í–¥ íšŒì „ê°’ ê¸°ì¤€
		FRotator Rotator = this->GetControlRotation();
		//í•´ë‹¹ íšŒì „ê°’ì˜ ê¸°ì¤€ì˜ ì• ë°©í–¥ì„ êµ¬í•´ì¤€ë‹¤.
		FVector Direction = UKismetMathLibrary::GetForwardVector(FRotator(0, Rotator.Yaw, 0));
		//ë°©í–¥ê³¼ í¬ê¸°ë¥¼ ì „ë‹¬í•¨. (ì‹œê°„ë§ˆë‹¤ ê±°ë¦¬ë¥¼ ë”í•˜ëŠ” ê²ƒì€ MovementComponentì—ì„œ, ì†ë„ ì„¸íŒ…ì€ movementcomponentì—ì„œ)
		this->GetPawn()->AddMovementInput(Direction, MovementVector.X);
	}
	//ì˜† ì´ë™
	if (MovementVector.Y != 0) {
		/*ë‚´ê°€ ë°”ë¼ë³´ëŠ” ê³³ ê¸°ì¤€ì˜ ì˜† ë°©í–¥ì„ êµ¬í•´ì¤Œ*/
		//ë§ˆìš°ìŠ¤ ë°©í–¥ íšŒì „ê°’ ê¸°ì¤€
		FRotator Rotator = this->GetControlRotation();
		//í•´ë‹¹ íšŒì „ê°’ì˜ ê¸°ì¤€ì˜ ì˜† ë°©í–¥ì„ êµ¬í•´ì¤€ë‹¤.
		FVector Direction = UKismetMathLibrary::GetRightVector(FRotator(0, Rotator.Yaw, 0));
		//ë°©í–¥ê³¼ í¬ê¸°ë¥¼ ì „ë‹¬í•¨. (ì‹œê°„ë§ˆë‹¤ ê±°ë¦¬ë¥¼ ë”í•˜ëŠ” ê²ƒì€ MovementComponentì—ì„œ, ì†ë„ ì„¸íŒ…ì€ movementcomponentì—ì„œ)
		this->GetPawn()->AddMovementInput(Direction, MovementVector.Y);
	}
}


