// Copyright_Team_AriAri


#include "Game/QGameModeVillage.h"
#include "QGameInstanceVillage.h"
#include "QVillageGameState.h"
#include "Player/QPlayerState.h"
#include "UObject/ConstructorHelpers.h"
#include "GodCall.h"
#include "Kismet/GameplayStatics.h"
#include "GameFramework/Actor.h"
#include "Engine/World.h"
#include "EngineUtils.h"
#include "JuryComponent.h"
#include "QLogCategories.h"
#include "ResidentComponent.h"
#include "Player/QPlayerController.h"


AQGameModeVillage::AQGameModeVillage()
{
	static ConstructorHelpers::FClassFinder<APawn> PlayerClassRef(TEXT("/Game/Blueprints/Character/BP_QLaywer.BP_QLaywer_C"));
	if (PlayerClassRef.Class) {	// ThirdPersonClassRef.Classê°€ nullì´ ì•„ë‹ˆë¼ë©´
		DefaultPawnClass = PlayerClassRef.Class;
	}
	static ConstructorHelpers::FClassFinder<APlayerController> PlayerControllerRef(TEXT("/Game/Blueprints/Player/BP_QPlayerController.BP_QPlayerController_C"));
	if (PlayerControllerRef.Class)
	{
		PlayerControllerClass = PlayerControllerRef.Class;
	}
	GameStateClass = AQVillageGameState::StaticClass();
	PlayerStateClass = AQPlayerState::StaticClass();
}

void AQGameModeVillage::PostInitializeComponents()
{
	Super::PostInitializeComponents();

	UE_LOG(LogTemp, Log, TEXT("ğŸ“Œ PostInitializeComponents() ì‹¤í–‰ë¨!"));
	/*UE_LOG(LogTemp, Log, TEXT("QGameModeVillage::PostInitializeComponents() - í”„ë¡¬í”„íŠ¸ ë¯¸ë¦¬ ì¤€ë¹„ ì‹œì‘"));

	GeneratePromptsBeforeNextGame();*/
}

void AQGameModeVillage::BeginPlay()
{
	Super::BeginPlay();
	
	// NPC ID ì¹´ìš´í„° ë¦¬ì…‹
	UJuryComponent::JuryCount = 0;
	UResidentComponent::ResidentCount = 0;
	UE_LOG(LogTemp, Log, TEXT("NPCID ì¹´ìš´í„° ì´ˆê¸°í™” ì™„ë£Œ (JuryCount = 0, ResidentCount = 0)"));


	UE_LOG(LogTemp, Log, TEXT("AAIGameModeTest::BeginPlay() ì‹¤í–‰ë¨"));

	UWorld* World = GetWorld();
	if (!World)
	{
		UE_LOG(LogTemp, Error, TEXT("âŒ BeginPlay - World is nullptr!"));
		return;
	}

	// ê¸°ì¡´ GodActor ì°¾ê¸°
	TArray<AActor*> FoundActors;
	UGameplayStatics::GetAllActorsWithTag(World, TEXT("GodActor"), FoundActors);

	if (FoundActors.Num() == 0 || !FoundActors[0])
	{
		UE_LOG(LogTemp, Error, TEXT("âŒ BeginPlay - GodActorë¥¼ ì°¾ì„ ìˆ˜ ì—†ìŒ!"));
		return;
	}

	AActor* GodActor = FoundActors[0];
	UGodCall* GodCall = GodActor->FindComponentByClass<UGodCall>();

	if (!GodCall)
	{
		UE_LOG(LogTemp, Error, TEXT("âŒ BeginPlay - GodCallì„ ì°¾ì„ ìˆ˜ ì—†ìŒ!"));
		return;
	}

	UE_LOG(LogTemp, Log, TEXT("âœ… BeginPlay - í”„ë¡¬í”„íŠ¸ ìƒì„± ì™„ë£Œ í›„ ê²Œì„ ì§„í–‰"));
}

void AQGameModeVillage::EndPlay(const EEndPlayReason::Type EndPlayReason)
{
	Super::EndPlay(EndPlayReason);

	UE_LOG(LogTemp, Log, TEXT("QGameModeVillage::EndPlay() - í”„ë¡¬í”„íŠ¸ ì‚­ì œ ë° ì¬ìƒì„± ì˜ˆì•½"));

	UQGameInstanceVillage* GameInstance = Cast<UQGameInstanceVillage>(GetGameInstance());
	if (GameInstance)
	{
		GameInstance->SchedulePromptRegeneration();
	}
	else
	{
		UE_LOG(LogTemp, Error, TEXT("âŒ GameInstanceë¥¼ ì°¾ì„ ìˆ˜ ì—†ìŒ! í”„ë¡¬í”„íŠ¸ ì¬ìƒì„± ì‹¤íŒ¨"));
	}

}

void AQGameModeVillage::TravelToCourtMap()
{
	if (!HasAuthority()) return;

	// ëª¨ë“  í”Œë ˆì´ì–´ê°€ ì¤€ë¹„ë˜ì§€ ì•Šì•˜ë‹¤ë©´ return
	for (TActorIterator<AQPlayerState> IT(GetWorld()); IT; ++IT)
	{
		if (!IT->GetIsReadyToTravelToCourt())
		{
			UE_LOG(LogLogic, Log, TEXT("AQVillageGameState::ServerRPCRequestTravelToCourt_Implementation - %s is not ready for travel to court."), *IT->GetName());
			return;
		}
	}
	
	// 1) GameMode ì—ì„œ seamless travel ì¼œê¸°
	bUseSeamlessTravel = true;

	// 2) ì„œë²„ ì£¼ë„ ë§µ ì „í™˜ (listen ëª¨ë“œ ìœ ì§€)
	GetWorld()->ServerTravel(TEXT("/Game/Maps/CourtMap?listen"));
}

void AQGameModeVillage::HandleSeamlessTravelPlayer(AController*& C)
{
	Super::HandleSeamlessTravelPlayer(C);

	// ê¸°ì¡´ Controllerë¥¼ ìƒˆë¡œìš´ Controllerë¡œ êµì²´
	APlayerController* OldPC = Cast<APlayerController>(C);
	if (OldPC)
	{
		UE_LOG(LogTemp, Warning, TEXT("Replacing PlayerController %s with VillageController"), *OldPC->GetName());

		// ë³µì‚¬í•´ ë‘˜ ì •ë³´
		FVector OldLocation = OldPC->GetPawn() ? OldPC->GetPawn()->GetActorLocation() : FVector::ZeroVector;
		FRotator OldRotation = OldPC->GetPawn() ? OldPC->GetPawn()->GetActorRotation() : FRotator::ZeroRotator;
		FString PlayerName = OldPC->PlayerState ? OldPC->PlayerState->GetPlayerName() : TEXT("Unknown");

		// ê¸°ì¡´ ì»¨íŠ¸ë¡¤ëŸ¬ ì œê±°
		OldPC->Destroy();

		// ìƒˆ ì»¨íŠ¸ë¡¤ëŸ¬ ìƒì„±
		FActorSpawnParameters SpawnParams;
		SpawnParams.Instigator = nullptr;
		SpawnParams.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AlwaysSpawn;
		AQPlayerController* NewPC = GetWorld()->SpawnActor<AQPlayerController>(AQPlayerController::StaticClass(), OldLocation, OldRotation, SpawnParams);

		NewPC->PlayerState->SetPlayerName(PlayerName);
		C = NewPC;  // ì¤‘ìš”: êµì²´ëœ ì»¨íŠ¸ë¡¤ëŸ¬ë¥¼ ì°¸ì¡°ë¡œ ë˜ëŒë ¤ ì¤˜ì•¼ í•¨

		// ìƒˆ Pawn ìŠ¤í°
		RestartPlayer(NewPC);
	}
}