// Copyright_Team_AriAri

#include "JuryComponent.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "HAL/PlatformFilemanager.h"
#include "JsonObjectConverter.h"
#include "GameFramework/PlayerState.h"
#include "GameFramework/PlayerController.h"
#include "Logging/LogMacros.h"

void UJuryComponent::BeginPlay()
{
    Super::BeginPlay();
    UE_LOG(LogTemp, Warning, TEXT("UJuryComponent::BeginPlay() ì‹¤í–‰ë¨ - NPC %s"), *NPCID);

    if (NPCID.IsEmpty())
    {
        // í˜„ì¬ ìƒì„±ëœ Resident ê°œìˆ˜ë¥¼ í™•ì¸
        // static int32 JuryCount = 0;

        NPCID = FString::FromInt(2001 + JuryCount);
        JuryCount++;

        UE_LOG(LogTemp, Log, TEXT("NPCID ìë™ í• ë‹¹ë¨: %s"), *NPCID);
    }

    // ë°°ì‹¬ì›ì˜ JSON íŒŒì¼ ê²½ë¡œ ì„¤ì •
    int32 JuryIndex = FCString::Atoi(*NPCID) - 2000; // NPCID 2001 -> JuryIndex 1

    if (JuryIndex < 1 || JuryIndex > 3)
        return;

    FString PromptFileName = FString::Printf(TEXT("PromptToJury%d.json"), JuryIndex);
    PromptFilePath = FPaths::ConvertRelativePathToFull(FPaths::Combine(FPaths::ProjectSavedDir(), TEXT("Prompt"), PromptFileName));

    UE_LOG(LogTemp, Log, TEXT("JuryComponent - NPC %sëŠ” %së¥¼ ì‚¬ìš©í•©ë‹ˆë‹¤."), *NPCID, *PromptFilePath);

    // ë°°ì‹¬ì› ë°ì´í„° ë¡œë“œ
    bool bLoaded = LoadPrompt();
    if (!bLoaded)
    {
        UE_LOG(LogTemp, Error, TEXT("í”„ë¡¬í”„íŠ¸ ë¡œë“œ ì‹¤íŒ¨ - NPCID: %s, íŒŒì¼: %s"), *NPCID, *PromptFilePath);
    }

    UE_LOG(LogTemp, Log, TEXT("BeginPlay ë - NPCID: %s, PromptContent ê¸¸ì´: %d"), *NPCID, PromptContent.Len());

}

void UJuryComponent::StartConversation(AQPlayerController* ClientPC, FOpenAIRequest Request)
{
    UE_LOG(LogTemp, Log, TEXT("ğŸ”µ JuryComponent::StartConversation ì‹¤í–‰ - NPCID: %s"), *NPCID);

    //Request.SpeakerID = FCString::Atoi(*GetPlayerIDAsString());
    //Request.ListenerID = GetNPCID();

    if (PromptContent.IsEmpty())
    {
        UE_LOG(LogTemp, Error, TEXT("PromptContentê°€ ë¹„ì–´ ìˆìŒ! NPCID: %s"), *NPCID);
        return;
    }

    UE_LOG(LogTemp, Log, TEXT("Player started conversation with NPC %d: %s"), Request.ListenerID, *Request.Prompt);

    FString ReadablePromptContent = UNPCComponent::ConvertJsonToReadableText(PromptContent);
    FString EscapedPlayerInput = Request.Prompt;

    UE_LOG(LogTemp, Log, TEXT("ë³€í™˜ëœ NPC ì„¤ì •: %s"), *ReadablePromptContent);

    FOpenAIRequest AIRequest;
    AIRequest.SpeakerID = Request.SpeakerID;
    AIRequest.ListenerID = Request.ListenerID;
    AIRequest.MaxTokens = 150;

    FString ListenerNPCID = FString::FromInt(Request.ListenerID);
    // ì²« ëŒ€í™”ì¸ì§€ í™•ì¸ (í”Œë ˆì´ì–´ì™€ì˜ P2N ëŒ€í™” ê¸°ë¡ì´ ì—†ëŠ” ê²½ìš°)
    bool bIsFirstGreeting = !P2NDialogueHistory.Contains(ListenerNPCID) ||
        P2NDialogueHistory[ListenerNPCID].DialogueLines.Num() == 0;

    // JSON ê°ì²´ ìƒì„±
    TSharedPtr<FJsonObject> RootObject = MakeShareable(new FJsonObject());
    RootObject->SetStringField("model", "gpt-4o");

    TArray<TSharedPtr<FJsonValue>> Messages;

    // system ë©”ì‹œì§€ ì¶”ê°€
    TSharedPtr<FJsonObject> SystemMessage = MakeShareable(new FJsonObject());
    SystemMessage->SetStringField("role", "system");

    // PStart (ì²« ëŒ€í™”)
    if (bIsFirstGreeting && Request.Prompt.IsEmpty()) 
    {
        AIRequest.ConversationType = EConversationType::PStart;

        SystemMessage->SetStringField("content",
            FString::Printf(TEXT("ë‹¹ì‹ ì€ ë°°ì‹¬ì› NPCì…ë‹ˆë‹¤. í”Œë ˆì´ì–´ê°€ ì²˜ìŒ ë‹¹ì‹ ê³¼ ëŒ€í™”í•  ë•Œ, "
                "ë‹¹ì‹ ì˜ ì„±ê²©ì— ë§ëŠ” ì§§ì€ ì²« ì¸ì‚¬ë¥¼ í•´ì•¼ í•©ë‹ˆë‹¤. ë‹¤ìŒì€ ë‹¹ì‹ ì˜ ì„¤ì •ì…ë‹ˆë‹¤.\n%s"),
                *ReadablePromptContent));
        Messages.Add(MakeShareable(new FJsonValueObject(SystemMessage)));

        TSharedPtr<FJsonObject> UserMessage = MakeShareable(new FJsonObject());
        UserMessage->SetStringField("role", "user");
        UserMessage->SetStringField("content", "ì•ˆë…•í•˜ì„¸ìš”! ë‹¹ì‹ ì€ ëˆ„êµ¬ì¸ê°€ìš”?");
        Messages.Add(MakeShareable(new FJsonValueObject(UserMessage)));
    }
    // P2N (ì¼ë°˜ ëŒ€í™”)
    else 
    {
        AIRequest.ConversationType = EConversationType::P2N;

        SystemMessage->SetStringField("content",
            FString::Printf(TEXT("ë‹¹ì‹ ì€ ë°°ì‹¬ì› NPCì…ë‹ˆë‹¤. ë‹¤ìŒì€ ë‹¹ì‹ ì˜ ì„¤ì •ì…ë‹ˆë‹¤.\n%s"),
                *ReadablePromptContent));
        Messages.Add(MakeShareable(new FJsonValueObject(SystemMessage)));

        // ì—¬ê¸°ì„œ `EscapedPlayerInput`ì„ OpenAI ìš”ì²­ì— ë°˜ì˜
        TSharedPtr<FJsonObject> UserMessage = MakeShareable(new FJsonObject());
        UserMessage->SetStringField("role", "user");
        UserMessage->SetStringField("content",
            FString::Printf(TEXT("í”Œë ˆì´ì–´ì˜ ì§ˆë¬¸: '%s'"), *EscapedPlayerInput));

        Messages.Add(MakeShareable(new FJsonValueObject(UserMessage)));
    }

    RootObject->SetArrayField("messages", Messages);
    RootObject->SetNumberField("max_tokens", 150);

    // JSONì„ ë¬¸ìì—´ë¡œ ë³€í™˜
    FString RequestBody;
    TSharedRef<TJsonWriter<>> Writer = TJsonWriterFactory<>::Create(&RequestBody);
    FJsonSerializer::Serialize(RootObject.ToSharedRef(), Writer);

    AIRequest.Prompt = RequestBody;

    UE_LOG(LogTemp, Log, TEXT("OpenAI ìµœì¢… ìš”ì²­ ë°ì´í„°(JSON): %s"), *RequestBody);

    RequestOpenAIResponse(AIRequest, [this, Request, ClientPC](FOpenAIResponse AIResponse)
        {
            if (AIResponse.ResponseText.IsEmpty())
            {
                AIResponse.ResponseText = TEXT("ì£„ì†¡í•©ë‹ˆë‹¤, ì§ˆë¬¸ì— ë‹µí•  ìˆ˜ ì—†ìŠµë‹ˆë‹¤.");
            }

            AIResponse.ConversationType = Request.ConversationType;
            AIResponse.SpeakerID = Request.SpeakerID;
            AIResponse.ListenerID = Request.ListenerID;
            ResponseCache.Add(Request.Prompt, AIResponse.ResponseText);
            SendNPCResponseToServer(AIResponse, ClientPC);
            SaveP2NDialogue(Request, AIResponse);
        });

}

int32 UJuryComponent::JuryCount = 0;