// Copyright_Team_AriAri


#include "NPCComponent.h"
#include "HttpModule.h"
#include "QLogCategories.h"
#include "Character/QDynamicNPC.h"
#include "Character/QPlayer.h"
#include "FramePro/FramePro.h"
#include "Game/QVillageGameState.h"
#include "Player/QPlayerController.h"
#include "Misc/FileHelper.h"
#include "UI/QVillageUIManager.h"
#include "UI/QP2NWidget.h"
#include "Misc/Paths.h"
#include "Templates/Function.h"
#include "GameFramework/PlayerState.h"
#include "GameFramework/PlayerController.h"
#include "Kismet/GameplayStatics.h"
#include "Net/UnrealNetwork.h"

// Sets default values for this component's properties
UNPCComponent::UNPCComponent()
{
	PrimaryComponentTick.bCanEverTick = false;
	LastConversationTime = FDateTime::MinValue();
}

FString UNPCComponent::GetPlayerIDAsString() const
{
	APlayerController* PC = GetWorld()->GetFirstPlayerController();
	if (!PC)
	{
		UE_LOG(LogTemp, Error, TEXT("GetPlayerIDAsString - PlayerController is nullptr!"));
		return TEXT("UnknownPlayer");
	}

	APlayerState* PS = PC->GetPlayerState<APlayerState>();
	if (!PS)
	{
		UE_LOG(LogTemp, Error, TEXT("GetPlayerIDAsString - PlayerState is nullptr!"));
		return TEXT("UnknownPlayer");
	}

	int32 PlayerID = PS->GetPlayerId();
	FString PlayerIDString = FString::FromInt(PlayerID);

	UE_LOG(LogTemp, Log, TEXT("GetPlayerIDAsString - PlayerID: %s"), *PlayerIDString);
	return PlayerIDString;
}

// Called when the game starts
void UNPCComponent::BeginPlay()
{
	Super::BeginPlay();

	UE_LOG(LogTemp, Log, TEXT("NPCComponent - NPC %s BeginPlay ì‹¤í–‰ë¨"), *GetOwner()->GetName());
}

void UNPCComponent::PerformNPCLogic()
{
	UE_LOG(LogTemp, Log, TEXT("Default NPC Logic"));
}

// NPCì˜ í”„ë¡¬í”„íŠ¸ íŒŒì¼ ë¡œë“œ
bool UNPCComponent::LoadPrompt()
{
	if (PromptFilePath.IsEmpty())
	{
		UE_LOG(LogTemp, Warning, TEXT("LoadPrompt ì‹¤í–‰ ì „ PromptFilePathê°€ ë¹„ì–´ ìˆìŒ! ê¸°ë³¸ ê²½ë¡œ ì„¤ì • ì‹œë„."));

		FString PromptFileName;

		// NPC ì—­í• (role)ì— ë”°ë¼ JSON íŒŒì¼ëª… ê²°ì •
		if (NPCRole == "resident")
		{
			PromptFileName = FString::Printf(TEXT("PromptToResident%d.json"), FCString::Atoi(*NPCID) - 2003);
		}
		else if (NPCRole == "jury")
		{
			PromptFileName = FString::Printf(TEXT("PromptToJury%d.json"), FCString::Atoi(*NPCID) - 2000);
		}
		else if (NPCRole == "defendant")
		{
			PromptFileName = TEXT("PromptToDefendant.json"); // DefendantëŠ” ë‹¨ í•˜ë‚˜ë§Œ ì¡´ì¬
		}
		else
		{
			UE_LOG(LogTemp, Error, TEXT("LoadPrompt - ì•Œ ìˆ˜ ì—†ëŠ” NPC Role: %s"), *NPCRole);
			return false;
		}

		// íŒŒì¼ ê²½ë¡œ ì„¤ì •
		PromptFilePath = FPaths::ConvertRelativePathToFull(FPaths::Combine(FPaths::ProjectSavedDir(), TEXT("Prompt"), PromptFileName));

		UE_LOG(LogTemp, Log, TEXT("LoadPrompt - NPCID: %s, Role: %s, íŒŒì¼ ê²½ë¡œ: %s"), *NPCID, *NPCRole, *PromptFilePath);
	}

	FString FileContent;

	if (!FFileHelper::LoadFileToString(FileContent, *PromptFilePath) || FileContent.IsEmpty())
	{
		UE_LOG(LogTemp, Error, TEXT("LoadPrompt ì‹¤íŒ¨ (íŒŒì¼ì´ ë¹„ì–´ ìˆìŒ) - %s"), *PromptFilePath);
		return false;
	}

	TSharedPtr<FJsonObject> JsonObject;
	TSharedRef<TJsonReader<>> Reader = TJsonReaderFactory<>::Create(FileContent);

	if (!FJsonSerializer::Deserialize(Reader, JsonObject) || !JsonObject.IsValid())
	{
		UE_LOG(LogTemp, Error, TEXT("JSON íŒŒì‹± ì‹¤íŒ¨ - %s"), *PromptFilePath);
		return false;
	}

	PromptContent = FileContent;

	// í•„ìˆ˜ í•„ë“œ í™•ì¸
	if (JsonObject->HasField("npcid"))
	{
		NPCID = FString::FromInt(JsonObject->GetIntegerField("npcid"));
		UE_LOG(LogTemp, Log, TEXT("LoadPrompt - NPCID í• ë‹¹ ì™„ë£Œ: %s"), *NPCID);
	}

	if (JsonObject->HasField("name"))
	{
		NPCName = JsonObject->GetStringField("name");
		UE_LOG(LogTemp, Log, TEXT("LoadPrompt - NPCName í• ë‹¹ ì™„ë£Œ: %s"), *NPCName);
	}

	if (JsonObject->HasField("role"))
	{
		NPCRole = JsonObject->GetStringField("role");
		UE_LOG(LogTemp, Log, TEXT("LoadPrompt - NPCRole í• ë‹¹ ì™„ë£Œ: %s"), *NPCRole);
	}

	UE_LOG(LogTemp, Log, TEXT("LoadPrompt ì™„ë£Œ - NPCID=%s, Name=%s, Role=%s"), *NPCID, *NPCName, *NPCRole);
	UE_LOG(LogTemp, Log, TEXT("PromptContent ì €ì¥ ì™„ë£Œ - ë‚´ìš©: %s"), *PromptContent.Left(200));

	return true;
}

/**
 * NPC ì„±ê²© Get/Set.
 */
 //FString UNPCComponent::GetNPCPersonality() const
 //{
 //	return NPCPersonality;
 //}

 //void UNPCComponent::SetNPCPersonality(const FString& NewPersonality)
 //{
 //	NPCPersonality = NewPersonality;
 //}

// OpenAI API í‚¤ ë¶ˆëŸ¬ì˜¤ê¸°
FString UNPCComponent::GetAPIKey()
{
	FString ConfigPath = FPaths::ProjectDir() + TEXT("OpenAIAuth.ini");
	FString FileContent;

	if (FFileHelper::LoadFileToString(FileContent, *ConfigPath))
	{
		UE_LOG(LogTemp, Log, TEXT("OpenAIAuth.ini ë¡œë“œ ì„±ê³µ"));
		FString ApiKey;
		if (FileContent.Split(TEXT("="), nullptr, &ApiKey))
		{
			return ApiKey.TrimStartAndEnd();
		}
	}

	UE_LOG(LogTemp, Error, TEXT("OpenAI API Key ë¡œë“œ ì‹¤íŒ¨! OpenAIAuth.ini í™•ì¸ í•„ìš”"));
	return TEXT("");
}

// OpenAI API ì‘ë‹µ JSON íŒŒì‹± í•¨ìˆ˜
FOpenAIResponse UNPCComponent::ParseAIResponse(FString ResponseContent)
{
	return FOpenAIResponse::FromJson(ResponseContent);
}

// NPC ì´ë¦„ ê°€ì ¸ì˜¤ê¸°
FString UNPCComponent::GetNPCName() const
{
	return NPCName;
}

int32 UNPCComponent::GetNPCID() const
{
	return FCString::Atoi(*NPCID);
}

bool UNPCComponent::GetIsFirstConversation() const
{
	return bIsFirstConversation;
}

bool UNPCComponent::GetIsRequestInProgress() const
{
	return bIsRequestInProgress;
}

FDateTime UNPCComponent::GetLastConversationTime() const
{
	return LastConversationTime;
}

void UNPCComponent::SetLastConversationTime(FDateTime NewLastConversationTime)
{
	LastConversationTime = NewLastConversationTime;
}

void UNPCComponent::GetLifetimeReplicatedProps(TArray<class FLifetimeProperty>& OutLifetimeProps) const
{
	Super::GetLifetimeReplicatedProps(OutLifetimeProps);

	DOREPLIFETIME(UNPCComponent, LastConversationTime);
}

// í˜„ì¬ AIì—ê²Œ ìš”ì²­ì„ ë³´ë‚¼ ìˆ˜ ìˆëŠ”ì§€ ì—†ëŠ”ì§€ íŒë‹¨
bool UNPCComponent::CanSendOpenAIRequest() const
{
	return !bIsRequestInProgress;
}

FString UNPCComponent::ConvertJsonToReadableText(const FString& JsonString)
{
	TSharedPtr<FJsonObject> JsonObject;
	TSharedRef<TJsonReader<>> Reader = TJsonReaderFactory<>::Create(JsonString);

	if (!FJsonSerializer::Deserialize(Reader, JsonObject) || !JsonObject.IsValid())
	{
		UE_LOG(LogTemp, Error, TEXT("ğŸš¨ JSON íŒŒì‹± ì‹¤íŒ¨! ì›ë³¸ ë°ì´í„° ë°˜í™˜"));
		return JsonString;
	}

	FString ReadableText;

	// NPC ê¸°ë³¸ ì •ë³´
	if (JsonObject->HasField("name"))
	{
		ReadableText += FString::Printf(TEXT("ì´ë¦„: %s\n"), *JsonObject->GetStringField("name"));
	}

	if (JsonObject->HasField("npcid"))
	{
		ReadableText += FString::Printf(TEXT("NPC ID: %d\n"), JsonObject->GetIntegerField("npcid"));
	}

	if (JsonObject->HasField("personality"))
	{
		ReadableText += FString::Printf(TEXT("ì„±ê²©: %s\n"), *JsonObject->GetStringField("personality"));
	}

	if (JsonObject->HasField("speech_style"))
	{
		ReadableText += FString::Printf(TEXT("ë§íˆ¬: %s\n"), *JsonObject->GetStringField("speech_style"));
	}

	if (JsonObject->HasField("situation_understanding"))
	{
		ReadableText += FString::Printf(TEXT("í˜„ì¬ ìƒí™© ì¸ì‹: %s\n"), *JsonObject->GetStringField("situation_understanding"));
	}

	if (JsonObject->HasField("past_life_relevance"))
	{
		ReadableText += FString::Printf(TEXT("ê³¼ê±° ê´€ë ¨ì„±: %s\n"), *JsonObject->GetStringField("past_life_relevance"));
	}

	if (JsonObject->HasField("past_life_story"))
	{
		ReadableText += FString::Printf(TEXT("ê³¼ê±° ì´ì•¼ê¸°: %s\n"), *JsonObject->GetStringField("past_life_story"));
	}

	if (JsonObject->HasField("knowledge_of_defendant's_past_life"))
	{
		ReadableText += FString::Printf(TEXT("í”¼ê³ ì¸ì˜ ê³¼ê±°ì— ëŒ€í•œ ì§€ì‹: %s\n"), *JsonObject->GetStringField("knowledge_of_defendant's_past_life"));
	}

	return ReadableText;
}


// P2N ëŒ€í™” ì‹œì‘
void UNPCComponent::StartConversation(AQPlayerController* ClientPC, FOpenAIRequest Request)
{
	UE_LOG(LogTemp, Log, TEXT("NPCComponent::StartConversation ì‹¤í–‰ - NPCID: %s"), *NPCID);
	UE_LOG(LogTemp, Log, TEXT("StartConversation ì‹¤í–‰ë¨ - í˜„ì¬ PromptContent ê¸¸ì´: %d"), PromptContent.Len());

	Request.SpeakerID = FCString::Atoi(*GetPlayerIDAsString());
	Request.ListenerID = GetNPCID();

	if (PromptContent.IsEmpty())
	{
		UE_LOG(LogTemp, Error, TEXT("ğŸš¨ PromptContentê°€ ë¹„ì–´ ìˆìŒ! NPCID: %s"), *NPCID);
		return;
	}

	UE_LOG(LogTemp, Log, TEXT("Player started conversation with NPC %d: %s"), Request.ListenerID, *Request.Prompt);

	FString ListenerNPCID = FString::FromInt(Request.ListenerID);
	bool bIsFirstGreeting = !P2NDialogueHistory.Contains(ListenerNPCID) ||
		P2NDialogueHistory[ListenerNPCID].DialogueLines.Num() == 0;

	FOpenAIRequest AIRequest;
	AIRequest.SpeakerID = Request.SpeakerID;
	AIRequest.ListenerID = Request.ListenerID;
	AIRequest.MaxTokens = 150;

	// OpenAIê°€ JSONì„ ì˜¬ë°”ë¥´ê²Œ í•´ì„í•  ìˆ˜ ìˆë„ë¡ ë³€í™˜
	FString ReadablePromptContent = ConvertJsonToReadableText(PromptContent);

	if (bIsFirstGreeting && Request.Prompt.IsEmpty())
	{
		AIRequest.ConversationType = EConversationType::PStart;
		AIRequest.Prompt = FString::Printf(TEXT(
			"{ \"model\": \"gpt-4o\", \"messages\": ["
			"{ \"role\": \"system\", \"content\": \"ë‹¹ì‹ ì€ ë§ˆì„ NPCì…ë‹ˆë‹¤. ë‹¤ìŒì€ NPCì˜ ì„¤ì •ì…ë‹ˆë‹¤: %s\" },"
			"{ \"role\": \"user\", \"content\": \"í”Œë ˆì´ì–´ê°€ NPCë¥¼ ì²˜ìŒ ë§Œë‚¬ì„ ë•Œ ë‹¹ì‹ ì´ í•  ì¸ì‚¬ëŠ”?\" }],"
			"\"max_tokens\": 150 }"
		), *ReadablePromptContent);
	}
	else
	{
		AIRequest.ConversationType = EConversationType::P2N;
		FString EscapedPlayerInput = Request.Prompt.Replace(TEXT("\n"), TEXT(" ")).Replace(TEXT("\""), TEXT("'"));
		AIRequest.Prompt = FString::Printf(TEXT(
			"{ \"model\": \"gpt-4o\", \"messages\": ["
			"{ \"role\": \"system\", \"content\": \"ë‹¹ì‹ ì€ ë§ˆì„ NPCì…ë‹ˆë‹¤. ë‹¤ìŒì€ NPCì˜ ì„¤ì •ì…ë‹ˆë‹¤: %s\" },"
			"{ \"role\": \"user\", \"content\": \"í”Œë ˆì´ì–´ì˜ ì§ˆë¬¸: '%s'\" }],"
			"\"max_tokens\": 150 }"
		), *ReadablePromptContent, *EscapedPlayerInput);
	}

	UE_LOG(LogTemp, Log, TEXT("OpenAI ìµœì¢… ìš”ì²­ ë°ì´í„°(JSON): %s"), *AIRequest.Prompt);

	RequestOpenAIResponse(AIRequest, [this, Request, ClientPC](FOpenAIResponse AIResponse)
		{
			if (AIResponse.ResponseText.IsEmpty())
			{
				AIResponse.ResponseText = TEXT("ì£„ì†¡í•©ë‹ˆë‹¤, ì§ˆë¬¸ì— ë‹µí•  ìˆ˜ ì—†ìŠµë‹ˆë‹¤.");
			}

			ResponseCache.Add(Request.Prompt, AIResponse.ResponseText);
			SendNPCResponseToServer(AIResponse, ClientPC);
			SaveP2NDialogue(Request, AIResponse);
		});
}


// N2N ëŒ€í™” ì‹œì‘
void UNPCComponent::StartNPCToNPCDialog(const FOpenAIRequest& Request)
{
	FString SpeakerNPCID = FString::FromInt(Request.SpeakerID);
	FString ListenerNPCID = FString::FromInt(Request.ListenerID);

	UE_LOG(LogTemp, Log, TEXT("StartNPCToNPCDialog ì‹œì‘: %s â†’ %s"), *SpeakerNPCID, *ListenerNPCID);

	FString PlayerDialogueSummary = TEXT("(í”Œë ˆì´ì–´ì™€ì˜ ëŒ€í™” ê¸°ë¡ ì—†ìŒ)");

	if (P2NDialogueHistory.Contains(SpeakerNPCID) && P2NDialogueHistory[SpeakerNPCID].DialogueLines.Num() > 0)
	{
		TArray<FString>& DialogueLines = P2NDialogueHistory[SpeakerNPCID].DialogueLines;
		int32 NumLines = DialogueLines.Num();

		FString RecentLines;
		int32 StartIndex = FMath::Max(0, NumLines - 3);
		for (int32 i = StartIndex; i < NumLines; i++)
		{
			RecentLines += DialogueLines[i] + TEXT(" ");
		}

		PlayerDialogueSummary = RecentLines.TrimEnd();
	}

	FString ReadablePromptContent = ConvertJsonToReadableText(PromptContent);
	FOpenAIRequest AIRequest;
	AIRequest.Prompt = FString::Printf(TEXT(
		"NPC '%s'ê°€ NPC '%s'ì—ê²Œ ë§ì„ ê²ë‹ˆë‹¤.\n"
		"ìµœê·¼ í”Œë ˆì´ì–´ì™€ ë‚˜ëˆˆ ëŒ€í™” ìš”ì•½: %s\n"
		"NPC '%s'ì˜ ì„±ê²©ì„ ë°˜ì˜í•´ ì²« ëŒ€í™”ë¥¼ ìƒì„±í•˜ì„¸ìš”."),
		*SpeakerNPCID, *ListenerNPCID, *PlayerDialogueSummary, *SpeakerNPCID);

	AIRequest.MaxTokens = 150;
	AIRequest.SpeakerID = Request.SpeakerID;
	AIRequest.ListenerID = Request.ListenerID;
	AIRequest.ConversationType = EConversationType::N2N;

	RequestOpenAIResponse(AIRequest, [this, ListenerNPCID, SpeakerNPCID](FOpenAIResponse AIResponse)
		{
			SendNPCResponseToServer(AIResponse);
			ContinueNPCToNPCDialog(FOpenAIRequest(AIResponse.ListenerID, AIResponse.SpeakerID, EConversationType::N2N, AIResponse.ResponseText, 4));
		});

	UE_LOG(LogTemp, Log, TEXT("NPC-to-NPC ëŒ€í™” ìš”ì²­ ì „ì†¡ ì™„ë£Œ"));
}


// N2N ëŒ€í™” ì´ì–´ë‚˜ê°
void UNPCComponent::ContinueNPCToNPCDialog(const FOpenAIRequest& Request)
{
	if (Request.MaxTokens <= 0)
	{
		UE_LOG(LogTemp, Log, TEXT("N2N ëŒ€í™”ê°€ ì¢…ë£Œë˜ì—ˆìŠµë‹ˆë‹¤."));
		return;
	}

	FString SpeakerNPCID = FString::FromInt(Request.SpeakerID);
	FString ListenerNPCID = FString::FromInt(Request.ListenerID);

	UE_LOG(LogTemp, Log, TEXT("ContinueNPCToNPCDialog: %s â†’ %s"), *SpeakerNPCID, *ListenerNPCID);

	// ìµœê·¼ ëŒ€í™” ë‚´ì—­ì„ ë°˜ì˜í•˜ì—¬ ì‘ë‹µ ìƒì„±
	FString PreviousResponse = Request.Prompt;
	FString ReadablePromptContent = ConvertJsonToReadableText(PromptContent);

	FOpenAIRequest AIRequest;
	AIRequest.Prompt = FString::Printf(TEXT(
		"NPC '%s'ê°€ NPC '%s'ì˜ ë§ì— ëŒ€ë‹µí•©ë‹ˆë‹¤.\n"
		"ì´ì „ ëŒ€í™”: %s\n"
		"ìì—°ìŠ¤ëŸ½ê³  ì¼ê´€ì„± ìˆëŠ” ëŒ€í™”ë¥¼ ì´ì–´ê°€ì„¸ìš”."),
		*SpeakerNPCID, *ListenerNPCID, *PreviousResponse);

	AIRequest.MaxTokens = Request.MaxTokens - 1;
	AIRequest.SpeakerID = Request.SpeakerID;
	AIRequest.ListenerID = Request.ListenerID;
	AIRequest.ConversationType = EConversationType::N2N;


	// OpenAI API í˜¸ì¶œ í›„, ëŒ€í™” ì´ì–´ë‚˜ê°€ê¸° (ë‚¨ì€ í„´ ìˆ˜ ê°ì†Œ)
	RequestOpenAIResponse(AIRequest, [this, Request](FOpenAIResponse AIResponse)
		{
			SendNPCResponseToServer(AIResponse);
			FOpenAIRequest NextRequest = Request;
			NextRequest.Prompt = AIResponse.ResponseText;  // AI ì‘ë‹µì„ ë‹¤ìŒ ë©”ì‹œì§€ë¡œ ì„¤ì •
			NextRequest.MaxTokens -= 1;  // ë‚¨ì€ í„´ ê°ì†Œ

			ContinueNPCToNPCDialog(NextRequest);
		});
}


// Ní˜¼ì£ë§ ìƒì„±
void UNPCComponent::PerformNPCMonologue(const FOpenAIRequest& Request)
{
	FString SpeakerNPCID = FString::FromInt(Request.SpeakerID);
	FString PlayerDialogueSummary = "(í”Œë ˆì´ì–´ì™€ ë‚˜ëˆˆ ëŒ€í™” ì—†ìŒ)";

	// P2N ëŒ€í™” ê¸°ë¡ì´ ì¡´ì¬í•˜ëŠ” ê²½ìš°ì—ë§Œ!! í•´ë‹¹ NPCì˜ ëŒ€í™” ê¸°ë¡ì„ ê¸°ë°˜ìœ¼ë¡œ í˜¼ì£ë§ ìƒì„±
	if (P2NDialogueHistory.Contains(SpeakerNPCID) && P2NDialogueHistory[SpeakerNPCID].DialogueLines.Num() > 0)
	{
		TArray<FString>& DialogueLines = P2NDialogueHistory[SpeakerNPCID].DialogueLines;
		int32 NumLines = DialogueLines.Num();

		FString RecentLines;
		int32 StartIndex = FMath::Max(0, NumLines - 3);
		for (int32 i = StartIndex; i < NumLines; i++)
		{
			RecentLines += DialogueLines[i] + TEXT(" ");
		}

		PlayerDialogueSummary = RecentLines.TrimEnd();
	}

	FOpenAIRequest AIRequest;
	AIRequest.Prompt = FString::Printf(TEXT(
		"NPC '%s'ê°€ í˜¼ì£ë§ì„ í•©ë‹ˆë‹¤.\n"
		"ìµœê·¼ í”Œë ˆì´ì–´ì™€ ë‚˜ëˆˆ ëŒ€í™” ìš”ì•½: %s\n"
		"NPCì˜ ì„±ê²©ê³¼ ê°ì •ì„ ë°˜ì˜í•˜ì—¬ í˜¼ì£ë§ì„ ìì—°ìŠ¤ëŸ½ê²Œ ìƒì„±í•˜ì„¸ìš”."),
		*SpeakerNPCID, *PlayerDialogueSummary);

	AIRequest.MaxTokens = 100;
	AIRequest.SpeakerID = Request.SpeakerID;
	AIRequest.ListenerID = 0; // í˜¼ì£ë§ì´ë¯€ë¡œ Listenerê°€ ì—†ìŒ
	AIRequest.ConversationType = EConversationType::NMonologue;

	RequestOpenAIResponse(AIRequest, [this, SpeakerNPCID](FOpenAIResponse AIResponse)
		{
			SendNPCResponseToServer(AIResponse);
			UE_LOG(LogTemp, Log, TEXT("NPC %sì˜ í˜¼ì£ë§: %s"), *SpeakerNPCID, *AIResponse.ResponseText);
		});
}

void UNPCComponent::TrialStatement(FOpenAIRequest Request)
{
	UE_LOG(LogTemp, Log, TEXT("ì¬íŒ ê´€ë ¨ AI ì‘ë‹µ ìš”ì²­ ì²˜ë¦¬ ì‹œì‘ (Type: %d)"), static_cast<int32>(Request.ConversationType));

	if (PromptContent.IsEmpty())
	{
		UE_LOG(LogTemp, Error, TEXT("PromptContentê°€ ë¹„ì–´ ìˆìŒ! NPCID: %s"), *NPCID);
		return;
	}

	// ê¸°ë³¸ ì„¤ì • (Speaker: NPC ID, Listener: í”Œë ˆì´ì–´ ID)
	Request.SpeakerID = GetNPCID();
	Request.ListenerID = FCString::Atoi(*GetPlayerIDAsString());

	FString ReadablePromptContent = UNPCComponent::ConvertJsonToReadableText(PromptContent);
	FString EscapedPlayerInput = Request.Prompt;

	// JSON ê°ì²´ ìƒì„±
	TSharedPtr<FJsonObject> RootObject = MakeShareable(new FJsonObject());
	RootObject->SetStringField("model", "gpt-4o");

	// ë©”ì‹œì§€ ë°°ì—´ ë¯¸ë¦¬ ì„ ì–¸
	TArray<TSharedPtr<FJsonValue>> Messages;
	TSharedPtr<FJsonObject> SystemMessage = MakeShareable(new FJsonObject());
	SystemMessage->SetStringField("role", "system");

	switch (Request.ConversationType)
	{
	case EConversationType::OpeningStatement:
	{
		Request.SpeakerID = GetNPCID(); // í”¼ê³ ì¸ì€ 2000
		Request.ListenerID = FCString::Atoi(*GetPlayerIDAsString());
		
		SystemMessage->SetStringField("content",
			FString::Printf(TEXT("í˜„ì¬ ë‹¹ì‹ ì€ ì¬íŒì¥ì— ì•‰ì•„ ë‹¹ì‹ ì˜ íŒê²°ì„ ê¸°ë‹¤ë¦¬ê³  ìˆëŠ” ì…ì¥ì…ë‹ˆë‹¤. ë‹¹ì‹ ì—ê²Œ ì¬íŒì´ ìœ ë¦¬í•´ì§€ë„ë¡, ë‹¹ì‹ ì˜ ì„¤ì •ì„ ë°˜ì˜í•˜ì—¬ ì§„ìˆ í•˜ì„¸ìš”: %s"),
				*ReadablePromptContent));
		Messages.Add(MakeShareable(new FJsonValueObject(SystemMessage)));
	}
		break;

	case EConversationType::EvidenceReview:
	{
		SystemMessage->SetStringField("content",
			FString::Printf(TEXT("ë‹¹ì‹ ì€ ì²œêµ­ê³¼ ì§€ì˜¥ì„ ê²°ì •í•˜ëŠ” ì¬íŒì˜ íŒì‚¬ì…ë‹ˆë‹¤. ë‹¤ìŒì€ ë‹¹ì‹ ì˜ ì„¤ì •ì…ë‹ˆë‹¤: %s"),
				*ReadablePromptContent));
		Messages.Add(MakeShareable(new FJsonValueObject(SystemMessage)));

		TSharedPtr<FJsonObject> UserMessage = MakeShareable(new FJsonObject());
		UserMessage->SetStringField("role", "user");
		UserMessage->SetStringField("content",
			FString::Printf(TEXT("ë‹¤ìŒì€ ê²€ì‚¬ì™€ ë³€í˜¸ì‚¬ê°€ ë‚˜ëˆˆ ëŒ€í™”ì…ë‹ˆë‹¤:\n%s\n"
				"ì´ ëŒ€í™”ë¥¼ ë³´ê³  íŒì‚¬ì˜ ì…ì¥ì—ì„œ ìš”ì•½í•´ì£¼ì„¸ìš”.\n"
				"í˜•ì‹: 'ê²€ì‚¬ì¸¡ì˜ ì£¼ì¥ì€ ~ì´ê³ , ë³€í˜¸ì‚¬ì¸¡ì˜ ì£¼ì¥ì€ ~ì´ì—ˆìŠµë‹ˆë‹¤.'"), *EscapedPlayerInput));
		Messages.Add(MakeShareable(new FJsonValueObject(UserMessage)));
	}
	break;

	case EConversationType::DefendantInterrogation:
	{
		SystemMessage->SetStringField("content",
			FString::Printf(TEXT("ë‹¹ì‹ ì€ ì¬íŒì„ ë°›ê³  ìˆëŠ” í”¼ê³ ì¸ì…ë‹ˆë‹¤. ë‹¤ìŒì€ ë‹¹ì‹ ì˜ ì „ìƒ ì •ë³´ì…ë‹ˆë‹¤:\n%s"),
				*ReadablePromptContent));
		Messages.Add(MakeShareable(new FJsonValueObject(SystemMessage)));

		TSharedPtr<FJsonObject> UserMessage = MakeShareable(new FJsonObject());
		UserMessage->SetStringField("role", "user");
		UserMessage->SetStringField("content",
			FString::Printf(TEXT("ê²€ì‚¬ í˜¹ì€ ë³€í˜¸ì‚¬ì˜ ì§ˆë¬¸: '%s'\në‹¹ì‹ ì˜ ì„±ê²©ê³¼ ê³¼ê±°ì— ë§ëŠ” ëŒ€ë‹µì„ í•´ì£¼ì„¸ìš”."), *EscapedPlayerInput));
		Messages.Add(MakeShareable(new FJsonValueObject(UserMessage)));
	}
	break;
	case EConversationType::JuryFinalOpinion:
	{
		SystemMessage->SetStringField("content",
			FString::Printf(TEXT("ë‹¹ì‹ ì€ ì¬íŒì„ ë°©ì²­í•˜ê³  ìˆëŠ” ë°°ì‹¬ì›ì…ë‹ˆë‹¤. ë‹¤ìŒì€ ë‹¹ì‹ ì˜ ì„±ê²© ë° ì„¤ì •ì…ë‹ˆë‹¤:\n%s"),
				*ReadablePromptContent));
		Messages.Add(MakeShareable(new FJsonValueObject(SystemMessage)));

		UQGameInstance* GameInstance = Cast<UQGameInstance>(GetWorld()->GetGameInstance());
		FString DialogueSummary;

		if (GameInstance)
		{
			const int32 NPCID = GetNPCID();
			TArray<FConversationRecord> Records = GameInstance->GetRecordWithNPCID(NPCID);

			if (Records.Num() > 0)
			{
				DialogueSummary = TEXT("ë‹¹ì‹ ì´ í”Œë ˆì´ì–´ë“¤ê³¼ ë‚˜ëˆˆ ëŒ€í™”:\n");

				for (const FConversationRecord& Record : Records)
				{
					DialogueSummary += FString::Printf(TEXT("- %s\n"), *Record.GetMessage());
				}
			}

			/*
			if (Records.Num() > 0)
			{
				DialogueSummary = TEXT("ë‹¤ìŒì€ ë‹¹ì‹ ì´ í”Œë ˆì´ì–´ë“¤ê³¼ ë‚˜ëˆˆ ëŒ€í™” ìš”ì•½ì…ë‹ˆë‹¤:\n");
				for (const FConversationRecord& Record : Records)
				{
					FString Role = (Record.GetSpeakerID() == NPCID) ? TEXT("ë‹¹ì‹ ") : TEXT("í”Œë ˆì´ì–´");
					DialogueSummary += FString::Printf(TEXT("[%s] %s\n"), *Role, *Record.GetMessage());
				}
			}
			*/
		}

		TSharedPtr<FJsonObject> UserMessage = MakeShareable(new FJsonObject());
		UserMessage->SetStringField("role", "user");
		UserMessage->SetStringField("content", FString::Printf(TEXT(
			"%s\n"
			"ì´ì œ í”Œë ˆì´ì–´ì— ëŒ€í•œ ë‹¹ì‹ ì˜ íŒë‹¨ì„ í•œ ë¬¸ì¥ìœ¼ë¡œ ì •ë¦¬í•´ì£¼ì„¸ìš”. ë°˜ë“œì‹œ ë‹¤ìŒ í•­ëª©ì„ í¬í•¨í•´ì•¼ í•©ë‹ˆë‹¤:\n"
			"1. í”¼ê³ ì¸ì˜ íƒœë„ë‚˜ ë§íˆ¬ì— ëŒ€í•œ ê°ìƒ\n"
			"2. ë‹¹ì‹ ì´ ë³€í˜¸ì‚¬ì™€ ê²€ì‚¬ ì¤‘ ëˆ„êµ¬ì˜ ì£¼ì¥ì„ ë” ì‹ ë¢°í•˜ëŠ”ì§€\n"
			"3. ë‹¹ì‹ ì˜ íŒë‹¨ ì´ìœ  (ê°„ë‹¨íˆ)\n\n"
			"4. ë‹¹ì‹ ì˜ ìºë¦­í„°ì„±ì„ ë°˜ì˜í•˜ì—¬, ëª…í™•íˆ 'ë‚˜ëŠ” ë³€í˜¸ì‚¬ë¥¼ ì§€ì§€í•œë‹¤' í˜¹ì€ 'ê²€ì‚¬ë¥¼ ì§€ì§€í•œë‹¤'ëŠ” ì˜ë¯¸ì˜ ë¬¸ì¥ì„ í¬í•¨í•˜ì„¸ìš”."), *DialogueSummary));
		Messages.Add(MakeShareable(new FJsonValueObject(UserMessage)));
	}
	break;

	case EConversationType::FinalVerdict:
	{
		SystemMessage->SetStringField("content",
			FString::Printf(TEXT(
				"ë‹¹ì‹ ì€ ì²œêµ­ê³¼ ì§€ì˜¥ì„ ê²°ì •í•˜ëŠ” ì¬íŒì˜ íŒì‚¬ì…ë‹ˆë‹¤. ë‹¤ìŒì€ ë‹¹ì‹ ì˜ ì„±ê²© ë° ì„¸ê³„ê´€ ì„¤ì •ì…ë‹ˆë‹¤:\n%s"),
				*ReadablePromptContent));
		Messages.Add(MakeShareable(new FJsonValueObject(SystemMessage)));

		FString DummyJurySummary = TEXT("- ë°°ì‹¬ì›1: í”¼ê³ ì¸ì˜ íƒœë„ê°€ ì§„ì‹¬ ê°™ì•˜ë‹¤\n- ë°°ì‹¬ì›2: ì¦ê±°ëŠ” ë¶€ì¡±í•˜ì§€ë§Œ ì˜ë„ê°€ ì¤‘ìš”í•˜ë‹¤ê³  ìƒê°í•œë‹¤");
		FString DummyEvidenceSummary = TEXT("- ì¦ê±°ë¬¼: í”¼ê³ ì¸ì´ ë²”í–‰ í˜„ì¥ì—ì„œ ë°œê²¬ëœ ë‹¨ê²€\n- ì§„ìˆ : í”¼ê³ ì¸ì€ ì •ë‹¹ë°©ìœ„ë¥¼ ì£¼ì¥í•¨");

		TSharedPtr<FJsonObject> UserMessage = MakeShareable(new FJsonObject());
		UserMessage->SetStringField("role", "user");

		UserMessage->SetStringField("content", FString::Printf(TEXT(
			"ë‹¹ì‹ ì€ ì§€ê¸ˆê¹Œì§€ ì¬íŒ ê³¼ì •ì„ ëª¨ë‘ ì§€ì¼œë³´ì•˜ìŠµë‹ˆë‹¤.\n"
			"ë‹¤ìŒì€ ë°°ì‹¬ì›ë“¤ì˜ ë°œì–¸ ìš”ì•½ì…ë‹ˆë‹¤:\n%s\n\n"
			"ë‹¤ìŒì€ í”¼ê³ ì¸ì˜ ëª¨ë‘ì§„ìˆ ê³¼ ì¦ê±° ìš”ì•½ì…ë‹ˆë‹¤:\n%s\n\n"
			"ì´ ëª¨ë“  ì •ë³´ë¥¼ ì¢…í•©í•˜ì—¬, ë‹¹ì‹ ì˜ íŒë‹¨ì„ ë‚´ë ¤ì£¼ì„¸ìš”. ë°˜ë“œì‹œ ë‹¤ìŒ í˜•ì‹ì„ ì§€ì¼œì•¼ í•©ë‹ˆë‹¤:\n\n"
			"1. íŒê²° ìš”ì•½: (ì˜ˆì‹œ: 'ê²€ì‚¬ì¸¡ì˜ ë…¼ë¦¬ëŠ” ì„¤ë“ë ¥ì´ ë¶€ì¡±í–ˆê³ , ë³€í˜¸ì‚¬ì˜ ì£¼ì¥ì´ ë” íƒ€ë‹¹í–ˆë‹¤.')\n"
			"2. ìµœì¢… íŒê²°: (ì˜ˆì‹œ: 'ë‚˜ëŠ” ë³€í˜¸ì‚¬ì˜ ì†ì„ ë“¤ì–´ì¤ë‹ˆë‹¤.')"),
			*DummyJurySummary,
			*DummyEvidenceSummary // ì¦ê±° ë° ëª¨ë‘ì§„ìˆ  ìš”ì•½
		));

		Messages.Add(MakeShareable(new FJsonValueObject(UserMessage)));
	}
	break;

	default:
		UE_LOG(LogTemp, Error, TEXT("TrialStatement: ì•Œ ìˆ˜ ì—†ëŠ” ConversationType ì…ë‹ˆë‹¤."));
		return;
	}

	// ë©”ì‹œì§€ ë°°ì—´ ì¶”ê°€
	RootObject->SetArrayField("messages", Messages);
	RootObject->SetNumberField("max_tokens", 250);

	// JSONì„ ë¬¸ìì—´ë¡œ ë³€í™˜ í›„ AIRequest.Promptì— ì €ì¥
	FString RequestBody;
	TSharedRef<TJsonWriter<>> Writer = TJsonWriterFactory<>::Create(&RequestBody);
	FJsonSerializer::Serialize(RootObject.ToSharedRef(), Writer);

	// AI ìš”ì²­ ìƒì„±
	FOpenAIRequest AIRequest;
	AIRequest.SpeakerID = Request.SpeakerID;
	AIRequest.ListenerID = Request.ListenerID;
	AIRequest.MaxTokens = 250;
	AIRequest.ConversationType = Request.ConversationType;
	AIRequest.Prompt = RequestBody;

	UE_LOG(LogTemp, Log, TEXT("OpenAI ìµœì¢… ìš”ì²­ ë°ì´í„°(JSON): %s"), *RequestBody);

	// AI ì‘ë‹µ ìš”ì²­
	RequestOpenAIResponse(AIRequest, [this](FOpenAIResponse AIResponse)
		{
			if (AIResponse.ResponseText.IsEmpty())
			{
				UE_LOG(LogTemp, Error, TEXT("AI ì‘ë‹µì´ ë¹„ì–´ ìˆìŒ!"));
				AIResponse.ResponseText = TEXT("ì‘ë‹µì´ ë¹„ì–´ ìˆìŠµë‹ˆë‹¤. DefendentComponent í™•ì¸ ìš”ë§");
			}

			UE_LOG(LogTemp, Log, TEXT("AI ì‘ë‹µ ì„±ê³µ: %s"), *AIResponse.ResponseText);

			// ì„œë²„ë¡œ ì „ì†¡
			SendNPCResponseToServer(AIResponse);

		});
}

// OpenAI API ìš”ì²­ ì²˜ë¦¬
void UNPCComponent::RequestOpenAIResponse(const FOpenAIRequest& AIRequest, TFunction<void(FOpenAIResponse)> Callback)
{
	if (!CanSendOpenAIRequest())
	{
		UE_LOG(LogTemp, Warning, TEXT("OpenAIê°€ í˜¸ì¶œ ì¤‘ì´ë¯€ë¡œ ìƒˆë¡œìš´ ìš”ì²­ì„ ë³´ë‚¼ ìˆ˜ ì—†ìŠµë‹ˆë‹¤."));
		return;
	}

	bIsRequestInProgress = true;

	FString ApiKey = GetAPIKey();
	if (ApiKey.IsEmpty())
	{
		UE_LOG(LogTemp, Error, TEXT("OpenAI API Keyê°€ ì—†ìŠµë‹ˆë‹¤!"));
		bIsRequestInProgress = false;
		return;
	}

	FString RequestBody = AIRequest.Prompt;
	UE_LOG(LogTemp, Log, TEXT("OpenAIì— ë³´ë‚¼ ìµœì¢… JSON ë°ì´í„°: %s"), *RequestBody);

	TSharedPtr<IHttpRequest> Request = FHttpModule::Get().CreateRequest();
	Request->SetURL("https://api.openai.com/v1/chat/completions");
	Request->SetVerb("POST");
	Request->SetHeader("Authorization", "Bearer " + ApiKey);
	Request->SetHeader("Content-Type", "application/json");
	Request->SetContentAsString(RequestBody);

	Request->OnProcessRequestComplete().BindLambda([this, Callback](FHttpRequestPtr Request, FHttpResponsePtr Response, bool bWasSuccessful)
		{
			bIsRequestInProgress = false;

			if (!bWasSuccessful || !Response.IsValid())
			{
				UE_LOG(LogTemp, Error, TEXT("OpenAI ìš”ì²­ ìì²´ê°€ ì‹¤íŒ¨í•¨!"));

				FOpenAIResponse FailedResponse;
				FailedResponse.ResponseText = TEXT("ì£„ì†¡í•©ë‹ˆë‹¤, í˜„ì¬ ë‹µë³€í•  ìˆ˜ ì—†ìŠµë‹ˆë‹¤.");
				Callback(FailedResponse);
				return;
			}

			int32 ResponseCode = Response->GetResponseCode();
			FString ResponseContent = Response->GetContentAsString();

			UE_LOG(LogTemp, Log, TEXT("OpenAI ì‘ë‹µ ì½”ë“œ: %d"), ResponseCode);
			UE_LOG(LogTemp, Log, TEXT("OpenAI ì‘ë‹µ ë³¸ë¬¸: %s"), *ResponseContent);

			if (ResponseCode != 200)
			{
				UE_LOG(LogTemp, Error, TEXT("OpenAI ì‘ë‹µ ì‹¤íŒ¨! HTTP ì‘ë‹µ ì½”ë“œ: %d"), ResponseCode);
				UE_LOG(LogTemp, Error, TEXT("OpenAI ì˜¤ë¥˜ ë©”ì‹œì§€: %s"), *ResponseContent);

				FOpenAIResponse FailedResponse;
				FailedResponse.ResponseText = TEXT("ì£„ì†¡í•©ë‹ˆë‹¤, í˜„ì¬ ë‹µë³€í•  ìˆ˜ ì—†ìŠµë‹ˆë‹¤.");
				Callback(FailedResponse);
				return;
			}

			// ì •ìƒ ì‘ë‹µ ì²˜ë¦¬
			FOpenAIResponse AIResponse = FOpenAIResponse::FromJson(ResponseContent);

			if (AIResponse.ResponseText.IsEmpty())
			{
				UE_LOG(LogTemp, Error, TEXT("OpenAI ì‘ë‹µì´ ë¹„ì–´ ìˆìŒ! ê¸°ë³¸ ì‘ë‹µ ë°˜í™˜."));
				AIResponse.ResponseText = TEXT("ì£„ì†¡í•©ë‹ˆë‹¤, ì§ˆë¬¸ì— ë‹µí•  ìˆ˜ ì—†ìŠµë‹ˆë‹¤.");
			}

			Callback(AIResponse);
		});

	Request->ProcessRequest();
}

TMap<FString, FString> ResponseCache;

// OpenAI APIì— ì¼ë°˜ ëŒ€í™” ìš”ì²­
void UNPCComponent::RequestAIResponse(const FString& PlayerInput)
{

	// OpenAI API ìš”ì²­
	FOpenAIRequest AIRequest;
	AIRequest.Prompt = FString::Printf(TEXT("'%s' ì„±ê²©ì„ ê°€ì§„ NPCê°€ í”Œë ˆì´ì–´ì˜ ì§ˆë¬¸ì— ë‹µë³€í•©ë‹ˆë‹¤.\n í”Œë ˆì´ì–´: \"%s\"\n NPC:"),
		*NPCPersonality, *PlayerInput);
	AIRequest.MaxTokens = 150;

	RequestOpenAIResponse(AIRequest, [this, PlayerInput](FOpenAIResponse AIResponse)
		{
			ResponseCache.Add(PlayerInput, AIResponse.ResponseText);
			UE_LOG(LogTemp, Log, TEXT("OpenAI Response: %s"), *AIResponse.ResponseText);
			SendNPCResponseToServer(AIResponse);
			OnNPCResponseReceived.Broadcast(AIResponse.ResponseText);
		});
}

void UNPCComponent::SaveP2NDialogue(const FOpenAIRequest& Request, const FOpenAIResponse& Response)
{
	FString NPCIDString = FString::FromInt(Request.ListenerID);

	if (!P2NDialogueHistory.Contains(NPCIDString))
	{
		P2NDialogueHistory.Add(NPCIDString, FDialogueHistory());
	}

	// í”Œë ˆì´ì–´ ì…ë ¥ì´ ìˆì„ ê²½ìš°ì—ë§Œ ì €ì¥í•´ì•¼ í•¨ (ì•ˆ ê·¸ëŸ¬ë©´ ì“°ë ˆê¸° ë°ì´í„°ê°€ ìƒê¹€)
	if (!Request.Prompt.IsEmpty())
	{
		P2NDialogueHistory[NPCIDString].DialogueLines.Add(FString::Printf(TEXT("Player: %s"), *Request.Prompt));
	}

	// NPC ì‘ë‹µì€ ë°”ë¡œ ì €ì¥
	P2NDialogueHistory[NPCIDString].DialogueLines.Add(FString::Printf(TEXT("NPC(%d): %s"), Response.SpeakerID, *Response.ResponseText));

	UE_LOG(LogTemp, Log, TEXT("P2N ëŒ€í™” ê¸°ë¡ ì €ì¥ ì™„ë£Œ - NPC: %s"), *NPCIDString);
}



// GetP2NDialogueHistory("NPCID")ë¥¼ í˜¸ì¶œí•˜ë©´ ëŒ€í™” ê¸°ë¡ì„ ê°€ì ¸ì˜¬ ìˆ˜ ìˆìŒ
TArray<FString> UNPCComponent::GetP2NDialogueHistory() const
{
	if (P2NDialogueHistory.Contains(NPCID))
	{
		return P2NDialogueHistory[NPCID].DialogueLines;
	}

	UE_LOG(LogTemp, Warning, TEXT("GetP2NDialogueHistory: No conversation history found for NPC %s"), *NPCID);
	return TArray<FString>(); // ê¸°ë¡ì´ ì—†ìœ¼ë©´ ë¹ˆ ë°°ì—´ ë°˜í™˜
}

// ì„œë²„ë¡œ NPCì˜ ì‘ë‹µì„ ë³´ë‚´ëŠ” RPC í•¨ìˆ˜
// ì„œë²„ë¡œ NPCì˜ ì‘ë‹µì„ ë³´ë‚´ëŠ” RPC í•¨ìˆ˜ (FOpenAIResponse ì „ì²´ ì „ë‹¬)
void UNPCComponent::SendNPCResponseToServer_Implementation(const FOpenAIResponse& Response, AQPlayerController* ClientPC)
{
	UE_LOG(LogLogic, Log, TEXT("SendNPCResponseToServer_Implementation Started"));
	if (!Response.ResponseText.IsEmpty() && Response.ResponseText != TEXT("ì£„ì†¡í•©ë‹ˆë‹¤, ë‹µë³€í•  ìˆ˜ ì—†ìŠµë‹ˆë‹¤."))
	{
		UE_LOG(LogTemp, Log, TEXT("Sending NPC response to server: %s"), *Response.ResponseText);
	}

	if (ClientPC->GetNetConnection() == nullptr)
	{
		UE_LOG(LogLogic, Log, TEXT("ClientPC %s NetConnection is nullptr."), *ClientPC->GetName());
		return;
	}
	
	UE_LOG(LogLogic, Log, TEXT("ClientPC Name : %s, NetConnection : %s"), *ClientPC->GetName(), *ClientPC->GetNetConnection()->GetName());

	switch (Response.ConversationType)
	{
	case EConversationType::PStart:
		UE_LOG(LogTemp, Log, TEXT("NPCì˜ ì²« ì¸ì‚¬(PStart) ì‘ë‹µ ì²˜ë¦¬"));
		break;
	case EConversationType::P2N:
		UE_LOG(LogTemp, Log, TEXT("P2N ëŒ€í™” ì‘ë‹µ ì²˜ë¦¬"));
		break;
	case EConversationType::N2N:
		UE_LOG(LogTemp, Log, TEXT("N2N ëŒ€í™” ì‘ë‹µ ì²˜ë¦¬"));
		break;
	case EConversationType::NMonologue:
		UE_LOG(LogTemp, Log, TEXT("NMonologue ëŒ€í™” ì‘ë‹µ ì²˜ë¦¬"));
		break;
	case EConversationType::OpeningStatement:
		UE_LOG(LogTemp, Log, TEXT("OpeningStatement ëª¨ë‘ì§„ìˆ  ì‘ë‹µ ì²˜ë¦¬"));
		break;
	default:
		UE_LOG(LogTemp, Error, TEXT("ì•Œ ìˆ˜ ì—†ëŠ” ConversationType ì²˜ë¦¬ ë¶ˆê°€"));
		return;
	}

	if (Response.SpeakerID == 0 && Response.ListenerID == 0)
	{
		UE_LOG(LogTemp, Error, TEXT("UNPCComponent::OnSuccessGetNPCResponse -> Invalid Response"))
		return;
	}
	if (!GetOwner()->HasAuthority())
	{
		UE_LOG(LogTemp, Log, TEXT("OnSuccessGetNPCResponse -> HasAuthority false."))
	}
	
	// ëŒ€í™”ê¸°ë¡ ì €ì¥
	SetLastConversationTime(FDateTime::Now());
	UQGameInstance* GameInstance = Cast<UQGameInstance>(GetWorld()->GetGameInstance());
	if (GameInstance == nullptr)
	{
		UE_LOG(LogTemp, Error, TEXT("OnSuccessStartConversation - GameInstance is null."));
		return;
	}
	int32 RecordID = GameInstance->AddConversationRecord(Response.ConversationType, Response.ListenerID, Response.SpeakerID, LastConversationTime, Response.ResponseText);
	if (RecordID < 0)
	{
		return;
	}
	AQPlayerState* PlayerState = GetWorld()->GetFirstPlayerController()->GetPlayerState<AQPlayerState>();
	const FConversationRecord* Record = PlayerState->GetRecordWithConvID(RecordID);
	UE_LOG(LogLogic, Log, TEXT("New Record - %d to %d : %s"), Record->GetSpeakerID(), Record->GetListenerID(), *Record->GetMessage());

	
	TObjectPtr<AQNPC> NPC = Cast<AQNPC>(GetOwner());	// QNPC
	if (NPC == nullptr)
	{
		UE_LOG(LogLogic, Error, TEXT("NPC Component's owner is not QNPC"));
		return;
	}

	// ì´í›„ í´ë¼ì´ì–¸íŠ¸ action í˜¸ì¶œ>
	switch (Response.ConversationType)
	{
	case EConversationType::PStart:
		UE_LOG(LogLogic, Log, TEXT("Server - PStart NPCResponse received"));
		ClientPC->ClientRPCStartConversation(Response, NPC);
		break;
	case EConversationType::P2N: 
		UE_LOG(LogLogic, Log, TEXT("Server - P2N NPCResponse received"));
		ClientPC->ClientRPCUpdateP2NResponse(Response);
		break;
	case EConversationType::N2N:
		break;
	case EConversationType::N2NStart:
		break;
	case EConversationType::NMonologue:
		break;
	case EConversationType::OpeningStatement:
		break;
	default:
		UE_LOG(LogTemp, Error, TEXT("GetNPCResponse -> Invaild ConversationType"));
		break;
	}
}

// Called every frame
void UNPCComponent::TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction)
{
	Super::TickComponent(DeltaTime, TickType, ThisTickFunction);

	// ...
}

// -------------------------------------------------------------------------------------- //

void UNPCComponent::ServerRPCGetNPCResponse_Implementation(AQPlayerController* ClientPC, FOpenAIRequest Request)
{
	/*
	 *	PStart, P2N : StartConversation, SendNPCResponseToServer()
	 *	N2N ëŒ€í™” ì‹œì‘ : StartNPCToNPCDialog, SendNPCResponseToServer()
	 *	N2N ëŒ€í™” ì§„í–‰ : ContinueNPCToNPCDialog(), SendNPCResponseToServer()
	 *	NMonologue : PerformNPCMonologue(), SendNPCResponseToServer()
	 */
	switch (Request.ConversationType)
	{
	case EConversationType::None:
		UE_LOG(LogTemp, Error, TEXT("GetNPCResponse -> Invaild ConversationType"));
		break;
	case EConversationType::N2N:
		UE_LOG(LogLogic, Log, TEXT("Server - N2N GetNPCResponse Started"));
		ContinueNPCToNPCDialog(Request);
		break;
	case EConversationType::N2NStart:
		UE_LOG(LogLogic, Log, TEXT("Server - N2NStart GetNPCResponse Started"));	
		StartNPCToNPCDialog(Request);
		break;
	case EConversationType::NMonologue:
		UE_LOG(LogLogic, Log, TEXT("Server - NMonologue GetNPCResponse Started"));
		PerformNPCMonologue(Request);
		break;
	case EConversationType::OpeningStatement:
		UE_LOG(LogLogic, Log, TEXT("Server - OpeningStatement GetNPCResponse Started"));
		PerformNPCMonologue(Request);
		break;
	default:	// typeì´ PStartë‚˜ P2Nì´ë¼ë©´
		UE_LOG(LogLogic, Log, TEXT("Server - PStart/P2N GetNPCResponse Started"));
		StartConversation(ClientPC, Request);
		break;
	}
}